name = "Play as Dragon Aether Edition"
author = "jcotton42, BlackAuresArt"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54849425e9ff3164b3ffdb8d201155691e564c57704aa6cc141153b85becca25"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
