name = "Play as Dragon Aether Edition"
author = "jcotton42, BlackAuresArt"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "559268c0e60f27f41a98c1ec67f35044d85cf6b533f948b5d0835d9009717aca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
