name = "Play as Dragon Aether Edition"
author = "jcotton42, BlackAuresArt"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c8cea7207b71cc4a9907fdec5c70843b1d05dc56aa83dd5f5325d9af3071732"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
