#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jun 04 07:08:15 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=10
shaderPack=ComplementaryReimagined_r5.8.1 + EuphoriaPatches_1.9.3
